### ISSUE TITLE
Bug on row 318

### ISSUE THREAD

**Issue by gubagu** [jcamenisch/jqTransform#1]
row 318:  $ul.parentsUntil is not a function
and the combobox does not get styled.

Greetz Guby

**Comment by jcamenisch** [comment]
Do you have a development page where I can see your code?

**Comment by jcamenisch** [comment]
And what version of jQuery are you using? It looks like parentsUntil was added in 1.4. http://api.jquery.com/parentsUntil/

**Comment by gubagu** [comment]
I got the code from this repo. Checked it the jquery this version using is 1.2.6. (required folder)
Changed the jquery to 1.6 and it worked like a charm thanks !

U probably need to update the jQuery version the repo uses.

Greetz

**Comment by jcamenisch** [comment]
Oh, that's hilarious. Obviously, this is different than what I'm using in production. Thanks for pointing it out so I can clean up the mess.
