### ISSUE TITLE
Unusable state

### ISSUE THREAD

**Issue by bozhinov** [jcamenisch/jqTransform#10]
Hello,

I m sorry to hear you abandoning the project.
Problem is that you also left it in unusable state
I reverted back to the one from 2009 which works fine for me.

If I ever get around to add input file and fix few problems I noticed I will commit here

Thank you for the code so far and good luck ahead

**Comment by jcamenisch** [comment]
:) You might try the very first commit, which is the exact code from http://www.dfc-e.com/metiers/multimedia/opensource/jqtransform/

If that works, you can use `git bisect` to narrow down where problem was introduced.
