### ISSUE TITLE
Is there a jqTransform + knockout.js implemenation?

### ISSUE THREAD

**Issue by jmogera** [jcamenisch/jqTransform#11]
I am using Knockout.js and jqTransform together and I can't get the controls to work together. Is there working solution to reference?

**Comment by jcamenisch** [comment]
No, I very much doubt it.

What are you using jqTransform to do?

**Comment by jmogera** [comment]
I use it make lot of controls look different! The only thing is I have used knockout.js with asp.net mvc3 extensively. I cannot proceed further until I figure it out, or use other way to design the checkbox, radiobutton, dropdown.

**Comment by jcamenisch** [comment]
Sorry this plugin isn't getting any love. I've only used it for drop-downs myself, and there are better options for that now.

For radio buttons and checkboxes, I would hope you can do all you need without javascript. See https://www.google.com/search?q=styling+radio+buttns+css3

It might depend on how far back you want to go with browser support. But this is cosmetic stuff we're talking about.
