### ISSUE TITLE
input width size

### ISSUE THREAD

**Issue by foria** [jcamenisch/jqTransform#7]
How can I customize the width size of the input field?

It doen't take 100% of the space box in rowElement.

thank you

**Comment by jcamenisch** [comment]
I'm afraid I've never used this plugin for input fields. I recommend styling them directly with css, without the use of javascript.

**Comment by foria** [comment]
yeah but when the plugin process my form give an inline style width to al my form input fields, I don't know how it calculate the width size... my issue is to get control of the automatic process on it.
thank you

**Comment by jcamenisch** [comment]
I would just use $(myForm).jqTransSelect() to transformt he selects. That will leave you in control of other elements.
