### ISSUE TITLE
How to set selected option value

### ISSUE THREAD

**Issue by navneetccna** [jcamenisch/jqTransform#8]
I want to set my select box value by jquery how will i achieve this ???

**Comment by jcamenisch** [comment]
You'll need to set the value of the select itself, as you would any normal select.

``` javascript
$('selector for desire select').val('blah').
```

**Comment by jcamenisch** [comment]
Just looking back through the code—it looks like the jqTransSelect component doesn't respond to the change event for the select. That should really be addressed from within the plugin, as you don't want other code in your page to have to know or care whether this plugin exists.

I'll apply a pull request if you'd like to get that working.

**Comment by sil2** [comment]
jqTransform is crap. Seriosly. Set new selected option is so big deal???

**Comment by jcamenisch** [comment]
@sil2, I believe your issue is covered in the README. ;)

**Comment by sil2** [comment]
spend 2 hours googling for an answer and finaly just did it this way:

var mySelect = $('#mySelect');  // original select for jqTransform
var dataValue = '%MYVALUE%' // required value
$(' option[value="'+dataValue+'"]',mySelect).attr('selected', 'selected');  // set original select 
var index = $("option:selected",mySelect).index(); // get index of selected option
mySelect.prev('ul').find('li').eq(index).find('a').click(); // update  jqTransform

this works, but shoud be a better way to select an option dynamicly.

**Comment by jcamenisch** [comment]
Yeah, I think if you're going to use a jQuery plugin, you'd want one that automatically responds to the change event. You should just be able to set the value of the select and expect everything else to just work.

Hence the recommendation to use a different plugin. Although, to be honest, I don't do this stuff with jQuery these days.
